//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerMaintenance.CustomerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ContactService", ConfigurationName="CustomerServiceReference.ContactService_Port")]
    public interface ContactService_Port {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ContactService:GetContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CustomerMaintenance.CustomerServiceReference.GetContact_Result GetContact(CustomerMaintenance.CustomerServiceReference.GetContact request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ContactService:GetContact", ReplyAction="*")]
        System.Threading.Tasks.Task<CustomerMaintenance.CustomerServiceReference.GetContact_Result> GetContactAsync(CustomerMaintenance.CustomerServiceReference.GetContact request);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdateContact_Result) of message UpdateContact_Result does not match the default value (UpdateContact)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ContactService:UpdateContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CustomerMaintenance.CustomerServiceReference.UpdateContact_Result UpdateContact(CustomerMaintenance.CustomerServiceReference.UpdateContact1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ContactService:UpdateContact", ReplyAction="*")]
        System.Threading.Tasks.Task<CustomerMaintenance.CustomerServiceReference.UpdateContact_Result> UpdateContactAsync(CustomerMaintenance.CustomerServiceReference.UpdateContact1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x74001")]
    public partial class ReadContact : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contactNoField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string addressField;
        
        private string postCodeField;
        
        private string cityField;
        
        private string phoneNoField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContactNo {
            get {
                return this.contactNoField;
            }
            set {
                this.contactNoField = value;
                this.RaisePropertyChanged("ContactNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("PostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
                this.RaisePropertyChanged("PhoneNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x74000")]
    public partial class UpdateContact : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contactNoField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string addressField;
        
        private string postCodeField;
        
        private string cityField;
        
        private string phoneNoField;
        
        private string emailField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContactNo {
            get {
                return this.contactNoField;
            }
            set {
                this.contactNoField = value;
                this.RaisePropertyChanged("ContactNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("PostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
                this.RaisePropertyChanged("PhoneNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContact", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ContactService", IsWrapped=true)]
    public partial class GetContact {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ContactService", Order=0)]
        public string hashCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ContactService", Order=1)]
        public CustomerMaintenance.CustomerServiceReference.ReadContact readContact;
        
        public GetContact() {
        }
        
        public GetContact(string hashCode, CustomerMaintenance.CustomerServiceReference.ReadContact readContact) {
            this.hashCode = hashCode;
            this.readContact = readContact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContact_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ContactService", IsWrapped=true)]
    public partial class GetContact_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ContactService", Order=0)]
        public CustomerMaintenance.CustomerServiceReference.ReadContact readContact;
        
        public GetContact_Result() {
        }
        
        public GetContact_Result(CustomerMaintenance.CustomerServiceReference.ReadContact readContact) {
            this.readContact = readContact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateContact", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ContactService", IsWrapped=true)]
    public partial class UpdateContact1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ContactService", Order=0)]
        public CustomerMaintenance.CustomerServiceReference.UpdateContact updateContact;
        
        public UpdateContact1() {
        }
        
        public UpdateContact1(CustomerMaintenance.CustomerServiceReference.UpdateContact updateContact) {
            this.updateContact = updateContact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateContact_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ContactService", IsWrapped=true)]
    public partial class UpdateContact_Result {
        
        public UpdateContact_Result() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContactService_PortChannel : CustomerMaintenance.CustomerServiceReference.ContactService_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactService_PortClient : System.ServiceModel.ClientBase<CustomerMaintenance.CustomerServiceReference.ContactService_Port>, CustomerMaintenance.CustomerServiceReference.ContactService_Port {
        
        public ContactService_PortClient() {
        }
        
        public ContactService_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactService_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactService_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactService_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CustomerMaintenance.CustomerServiceReference.GetContact_Result CustomerMaintenance.CustomerServiceReference.ContactService_Port.GetContact(CustomerMaintenance.CustomerServiceReference.GetContact request) {
            return base.Channel.GetContact(request);
        }
        
        public void GetContact(string hashCode, ref CustomerMaintenance.CustomerServiceReference.ReadContact readContact) {
            CustomerMaintenance.CustomerServiceReference.GetContact inValue = new CustomerMaintenance.CustomerServiceReference.GetContact();
            inValue.hashCode = hashCode;
            inValue.readContact = readContact;
            CustomerMaintenance.CustomerServiceReference.GetContact_Result retVal = ((CustomerMaintenance.CustomerServiceReference.ContactService_Port)(this)).GetContact(inValue);
            readContact = retVal.readContact;
        }
        
        public System.Threading.Tasks.Task<CustomerMaintenance.CustomerServiceReference.GetContact_Result> GetContactAsync(CustomerMaintenance.CustomerServiceReference.GetContact request) {
            return base.Channel.GetContactAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CustomerMaintenance.CustomerServiceReference.UpdateContact_Result CustomerMaintenance.CustomerServiceReference.ContactService_Port.UpdateContact(CustomerMaintenance.CustomerServiceReference.UpdateContact1 request) {
            return base.Channel.UpdateContact(request);
        }
        
        public void UpdateContact(CustomerMaintenance.CustomerServiceReference.UpdateContact updateContact1) {
            CustomerMaintenance.CustomerServiceReference.UpdateContact1 inValue = new CustomerMaintenance.CustomerServiceReference.UpdateContact1();
            inValue.updateContact = updateContact1;
            CustomerMaintenance.CustomerServiceReference.UpdateContact_Result retVal = ((CustomerMaintenance.CustomerServiceReference.ContactService_Port)(this)).UpdateContact(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CustomerMaintenance.CustomerServiceReference.UpdateContact_Result> CustomerMaintenance.CustomerServiceReference.ContactService_Port.UpdateContactAsync(CustomerMaintenance.CustomerServiceReference.UpdateContact1 request) {
            return base.Channel.UpdateContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<CustomerMaintenance.CustomerServiceReference.UpdateContact_Result> UpdateContactAsync(CustomerMaintenance.CustomerServiceReference.UpdateContact updateContact) {
            CustomerMaintenance.CustomerServiceReference.UpdateContact1 inValue = new CustomerMaintenance.CustomerServiceReference.UpdateContact1();
            inValue.updateContact = updateContact;
            return ((CustomerMaintenance.CustomerServiceReference.ContactService_Port)(this)).UpdateContactAsync(inValue);
        }
    }
}
